# Generated by Django 4.0.6 on 2022-07-29 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-brand',), 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='sale_detail',
            options={'ordering': ('price',), 'verbose_name_plural': 'sale_details'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('-name',), 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('-name',), 'verbose_name_plural': 'subcategories'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
